version: '3'

services:
  pritunl:
    image: 'jippi/pritunl:1.30.3157.70'
    privileged: true
    ports:
#       - '80:80'
      - '127.0.0.1:8443:443'
      - '1194:1194/udp'
#       - '1194:1194/tcp'
    volumes:
      - './pritunl_data:/var/lib/pritunl'
      - './pritunl_db:/var/lib/mongodb'


